services:
  mostaql-notifier:
    build: .
    # image: ghcr.io/tuttrue/mostaql_notifier:latest
    container_name: mostaql-notifier
    restart: unless-stopped
    volumes:
      # Mount logs directory to persist logs on host
      - ./logs:/app/logs
      # Optional: Mount a config file if you want to update cookies without rebuilding
      - ./config:/app/config:ro
    environment:
      - TZ=UTC
      - MOSTAQLWEB=eyJpdiI6InlmS254NVp5MVVVUXBqMVNzcndmd2c9PSIsInZhbHVlIjoidWVBTTBIWTFpSFd5aENCQVA1YWJKR1l0bHpnODBZNkJ1RGREdTlFL0xOZTdFa0VlUUxkRTlxS2NZR1Jhd2sxVkoyZnlZQTlnU1U4LzEvV2wzWVVDMVltS08rcExhclFubjJnTzNIRE9YU2lSaDVRWUQvWjM0MVRBeVBPdWZtdHQiLCJtYWMiOiI4ZDlkZTcwZjI4MDU1NWI0MmE2NDYwYWM1MDczOTY3YWFjMmFlMTY5MDBlMjc2MjcxYzNhMDAwZmMxYzM0NWUwIiwidGFnIjoiIn0%3D
    # Optional: Add health check
    healthcheck:
      test: ["CMD", "pgrep", "cron"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    # Optional: Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

